
name: Production Deployment

on:
  workflow_dispatch:
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Extract Short SHA
        id: extract_sha_short
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REG_URL }}
          username: ${{ secrets.REG_USER }}
          password: ${{ secrets.REG_PASS }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        env:
          SKIP_ENV_VALIDATION: true
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ secrets.REG_URL }}/moneyger:latest
            ${{ secrets.REG_URL }}/moneyger:${{ steps.extract_sha_short.outputs.sha_short }}
          build-args: |
            COMMIT=${{ steps.extract_sha_short.outputs.sha_short }}
            APP_VERSION=${{ steps.extract_sha_short.outputs.sha_short }}
            NEXT_PUBLIC_APP_URL=https://moneyger.dev
            NEXT_PUBLIC_ENVIRONMENT=production